### ISSUE TITLE
Make a binary ready for download!

### ISSUE THREAD

**Issue by MKGitHub** [fpg1503/MakeXcodeGr8Again#25]
Make a binary ready for download!
Hate having to build stuff when the app should be already built and ready for download!

**Comment by fpg1503** [comment]
This is intentional since Xcode has to be opened at least once before being grated (see #3) and so people can be sure it's the real deal (and not a binary injecting some malicious code in their Xcode).

Considering your request I'll upload a binary to releases with a full disclaimer. I'll close this issue when I'm done.
